"""O contrato central: metadado sai, pixel fica."""

from __future__ import annotations

import io
import struct
import zlib

import pytest
from PIL import Image

from metadata_scrubber.report import UnsupportedFormat
from metadata_scrubber.scrub import scrub_bytes


def _sample(fmt: str, **kwargs) -> bytes:
    image = Image.new("RGB", (32, 24), (10, 120, 200))
    buffer = io.BytesIO()
    image.save(buffer, format=fmt, **kwargs)
    return buffer.getvalue()


def _pixels(data: bytes) -> bytes:
    with Image.open(io.BytesIO(data)) as image:
        return image.convert("RGB").tobytes()


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    body = ctype + payload
    return struct.pack(">I", len(payload)) + body + struct.pack(">I", zlib.crc32(body))


def _inject_png_chunk(data: bytes, ctype: bytes, payload: bytes) -> bytes:
    """Insere um chunk logo apos o IHDR."""
    head_end = 8 + 25  # assinatura + IHDR completo
    return data[:head_end] + _png_chunk(ctype, payload) + data[head_end:]


# --- PNG ------------------------------------------------------------------


def test_png_remove_c2pa_e_preserva_pixel():
    original = _inject_png_chunk(_sample("PNG"), b"caBX", b"jumb" + b"\x00" * 512)

    cleaned, report = scrub_bytes(original)

    assert report.fmt == "PNG"
    assert b"caBX" not in cleaned
    assert any(item.kind == "caBX" for item in report.removed)
    assert _pixels(cleaned) == _pixels(original)


def test_png_remove_texto_e_data():
    original = _inject_png_chunk(_sample("PNG"), b"tEXt", b"Software\x00Generated by AI")
    original = _inject_png_chunk(original, b"tIME", b"\x07\xe9\x09\x16\x08\x00\x00")

    cleaned, report = scrub_bytes(original)

    assert b"Generated by AI" not in cleaned
    kinds = {item.kind for item in report.removed}
    assert {"tEXt", "tIME"} <= kinds


def test_png_ja_limpo_nao_muda():
    original = _sample("PNG")

    cleaned, report = scrub_bytes(original)

    assert report.is_clean
    assert cleaned == original


def test_png_trailer_depois_do_iend_sai():
    original = _sample("PNG") + b"payload escondido"

    cleaned, report = scrub_bytes(original)

    assert b"payload escondido" not in cleaned
    assert any(item.kind == "trailer" for item in report.removed)


def test_png_icc_condicional():
    original = _inject_png_chunk(_sample("PNG"), b"iCCP", b"perfil\x00\x00" + zlib.compress(b"x"))

    mantido, _ = scrub_bytes(original, keep_icc=True)
    removido, report = scrub_bytes(original, keep_icc=False)

    assert b"iCCP" in mantido
    assert b"iCCP" not in removido
    assert any(item.kind == "iCCP" for item in report.removed)


# --- JPEG -----------------------------------------------------------------


def test_jpeg_remove_exif_e_preserva_pixel():
    exif = Image.Exif()
    exif[0x0110] = "Camera Secreta"
    exif[0x013B] = "vitor"
    original = _sample("JPEG", exif=exif, quality=90)
    assert b"Camera Secreta" in original

    cleaned, report = scrub_bytes(original)

    assert report.fmt == "JPEG"
    assert b"Camera Secreta" not in cleaned
    assert _pixels(cleaned) == _pixels(original)


def test_jpeg_remove_comentario():
    original = _sample("JPEG", comment=b"feito com IA")

    cleaned, report = scrub_bytes(original)

    assert b"feito com IA" not in cleaned
    assert any(item.kind == "COM" for item in report.removed)


def test_jpeg_preserva_jfif():
    original = _sample("JPEG")

    cleaned, _ = scrub_bytes(original)

    assert b"JFIF" in cleaned
    assert _pixels(cleaned) == _pixels(original)


def test_jpeg_progressivo_sobrevive():
    exif = Image.Exif()
    exif[0x0110] = "Camera Secreta"
    original = _sample("JPEG", exif=exif, progressive=True, quality=85)

    cleaned, _ = scrub_bytes(original)

    assert b"Camera Secreta" not in cleaned
    assert _pixels(cleaned) == _pixels(original)


# --- WebP -----------------------------------------------------------------


def test_webp_remove_exif_e_xmp():
    exif = Image.Exif()
    exif[0x0110] = "Camera Secreta"
    original = _sample("WEBP", exif=exif, xmp=b"<x:xmpmeta>segredo</x:xmpmeta>", lossless=True)

    cleaned, report = scrub_bytes(original)

    assert report.fmt == "WebP"
    assert b"Camera Secreta" not in cleaned
    assert b"segredo" not in cleaned
    assert _pixels(cleaned) == _pixels(original)


def test_webp_limpa_flags_do_vp8x():
    exif = Image.Exif()
    exif[0x0110] = "Camera Secreta"
    original = _sample("WEBP", exif=exif, lossless=True)

    cleaned, _ = scrub_bytes(original)

    index = cleaned.find(b"VP8X")
    if index != -1:  # so ha VP8X quando existe alguma feature estendida
        assert cleaned[index + 8] & 0x08 == 0  # bit de EXIF desligado


# --- GIF ------------------------------------------------------------------


def test_gif_remove_comentario():
    original = _sample("GIF", comment=b"marca de agua")

    cleaned, report = scrub_bytes(original)

    assert report.fmt == "GIF"
    assert b"marca de agua" not in cleaned
    assert _pixels(cleaned) == _pixels(original)


def test_gif_animado_mantem_loop():
    # Cores distintas de verdade: frames identicos seriam colapsados num so
    # pelo proprio Pillow, e o teste passaria a nao testar nada.
    cores = [(255, 0, 0), (0, 255, 0), (0, 0, 255)]
    frames = [Image.new("RGB", (16, 16), c).convert("P") for c in cores]
    buffer = io.BytesIO()
    frames[0].save(
        buffer, format="GIF", save_all=True, append_images=frames[1:], loop=0, duration=100
    )
    original = buffer.getvalue()

    cleaned, _ = scrub_bytes(original)

    assert b"NETSCAPE2.0" in cleaned
    with Image.open(io.BytesIO(cleaned)) as image:
        assert image.n_frames == 3


# --- Dispatch -------------------------------------------------------------


def test_formato_desconhecido_falha_explicito():
    with pytest.raises(UnsupportedFormat):
        scrub_bytes(b"%PDF-1.7\n nao e imagem")


def test_arquivo_vazio_falha_explicito():
    with pytest.raises(UnsupportedFormat):
        scrub_bytes(b"")


def test_identificacao_por_assinatura_nao_por_extensao():
    """Um JPEG renomeado para .png ainda e tratado como JPEG."""
    original = _sample("JPEG", quality=90)

    _, report = scrub_bytes(original)

    assert report.fmt == "JPEG"
